python pagerank.py "distiluse-base-multilingual-cased-v1" "scientific_papers/arxiv" "None"
python pagerank.py "distiluse-base-multilingual-cased-v2" "scientific_papers/arxiv" "None"
python pagerank.py "distiluse-base-multilingual-cased-v1" "scientific_papers/arxiv" "EnglishStemmer"
python pagerank.py "multi-qa-MiniLM-L6-cos-v1" "scientific_papers/arxiv" "None"
python pagerank.py "multi-qa-distilbert-cos-v1" "scientific_papers/arxiv" "None"
